### ISSUE TITLE
Wikipakk tree issues

### ISSUE THREAD

**Issue by Alin-Dumitrescu** [WikiTransformationProject/wikitraccs-releases#48] opened 2023-05-26 01:23 UTC
Hello,

I am evaluating wikipakk for a confluence site migrated to SharePoint with WikiTracs. It seems during the migration the hierarchy of the pages was not preserved - all pages are now listed in a flat list - what am I doing wrong?

Thanks, Alin

**Comment by heinrich-ulbricht** [comment] 2023-05-26 08:23
@Alin-Dumitrescu This should work out of the box, so I think you are doing everything right.

Which version of WikiPakk are you using? From AppSource or GitHub, and which version number? There is a small question mark beneath the page tree that opens a dialog showing the version. Make sure it's the (as of now) latest version v2.2.2.

For the SharePoint page tree to show the Confluence page hierarchy certain metadata is needed. WikiTraccs should carry this metadata over when migrating pages from Confluence to Sharepoint.

Let's check if this metadata is present.

In SharePoint, please open the **migration target site** - that's the site WikiTraccs is migrating the Confluence pages to. Choose **Site Contents** and open the **Site Pages** library. There should be pages in there that have been migrated already.

Add the following existing columns to the current view, if they are not already shown:

* Confluence: Id (WikiTraccs)
* Confluence: Parent Id (WikiTraccs)
* Confluence: Sibling Order (WikiTraccs)

This should look something like this:

![image](https://github.com/WikiTransformationProject/wikitraccs-releases/assets/3469970/5e0b6400-29b7-40a2-bd11-588bd3672268)

Those IDs are Confluence page IDs, parent and child, plus the order from the Confluence page tree.

Are there values in those columns for migrated pages? If no, we have to look at the migration and why those values didn't carry over. If yes, we have to look at what WikiPakk does not like about them.

Feel free to post screenshots of the Site Pages Library view, WikiPakk showing the flat "hierarchy", or the JavaScript console filtered for "WikiPakk" messages. If they contain information not for the public eye, blur them where necessary or send them to contact - at - wikitransformationproject.com, referencing this issue here. Thank you!

**Comment by Alin-Dumitrescu** [comment] 2023-05-26 15:27
Hi Heinrich,

I do see the information listed below and it looks correct. If you want to schedule a meeting to review this in more details, just let me know

***@***.***

The tree is flat, all items have the expand symbol ( > ) and if I click on the expand symbol, it will try to retrieve pages and eventually disappear.
***@***.***

Thank you,
Alin Dumitrescu
Azure DevOps Consultant
phone (425) 279-3465

**Comment by heinrich-ulbricht** [comment] 2023-05-29 20:52
Having a quick call sounds like a good suggestion because this is difficult to diagnose without seeing it. You can use the [booking page](https://outlook.office365.com/owa/calendar/bookingswtpsupport@wikitransformationproject.com/bookings/) to choose a time that hopefully fits your schedule. Thanks!

**Comment by Alin-Dumitrescu** [comment] 2023-05-30 01:13
I am on the PST time (GMT-8). I see there is a 7:00 AM my time available on Tue June 6th. Any chance there is a spot at the same time or later sooner?

Thank you,
Alin Dumitrescu
Azure DevOps Consultant
phone (425) 279-3465

**Comment by heinrich-ulbricht** [comment] 2023-05-30 11:15
@Alin-Dumitrescu Ah timezones :D I added two later options Thursday and Tuesday - how about that?

**Comment by Alin-Dumitrescu** [comment] 2023-05-30 14:46
I got that time and was able to schedule at 12:00 PM thank you. Talk to you soon!

Thank you,
Alin Dumitrescu
Azure DevOps Consultant
phone (425) 279-3465

**Comment by heinrich-ulbricht** [comment] 2023-06-02 21:43
Further analysis showed that page metadata for some SharePoint pages was missing. The page tree thus had no information of the parent child relationship of those pages, displaying them at the root. This is expected behavior.

The solution in this case was to delete and remigrate the affected pages.

Closing this issue. Feel free to open a new one if there are other issues.

**Closed by heinrich-ulbricht** 2023-06-02 21:43 UTC
Labels: type:bug-suspected
